apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  mongo.api: 'mongodb://{{ .Values.mongo.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.mongo.containerPort }}/cinema'
  server.api: 'http://{{ .Values.server.name }}-{{ .Values.namespace }}.apps.klhymc1rs8d4802948.westeurope.aroapp.io/api'

