kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.server.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.servicePort }}
      targetPort: {{ .Values.server.serviceTargetPort }}
  type: ClusterIP

